import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/footer";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div>
					<header className="bg-primary p-4 text-white">
						<nav className="container mx-auto flex justify-between">
							<Link href="/">
								<div className="text-xl font-bold cursor-pointer">
									Health Software Solution
								</div>
							</Link>
							<ul className="flex space-x-4">
								<li>
									<Link href="/">Home</Link>
								</li>
								<li>
									<Link href="/about">About Us</Link>
								</li>
								<li>
									<Link href="/services">Services</Link>
								</li>
								<li>
									<Link href="/contact">Contact</Link>
								</li>
							</ul>
						</nav>
					</header>
					<main>{children}</main>
					<Footer />
				</div>
			</body>
		</html>
	);
}
