import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<div>
					<header className="bg-primary p-4 text-white">
						<nav className="container mx-auto flex justify-between">
							<div className="text-xl font-bold">Health Software Solution</div>
							<ul className="flex space-x-4">
								<li>
									<a href="/">Home</a>
								</li>
								<li>
									<a href="/about">About Us</a>
								</li>
								<li>
									<a href="/services">Services</a>
								</li>
								<li>
									<a href="/contact">Contact</a>
								</li>
							</ul>
						</nav>
					</header>
					<main>{children}</main>
					<footer className="bg-secondary p-4 text-white text-center">
						<p>&copy; 2024 Health Software Solution</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
